# Generated by Django 5.2.7 on 2025-10-27 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_items_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='item_name',
            field=models.CharField(max_length=200),
        ),
    ]
